### ISSUE TITLE
Default socket path causes ReferenceError on Windows

### ISSUE THREAD

**Issue by mateodelnorte** [dshaw/replify#10]
The default socket path causes an error on Windows (for two reasons): 1) /tmp/repl doesn't exist on Windows, but also 2) when attempting to log the error replDir is referenced instead of options.path and replDir is not an instantiated var. 

issue 2:

```
PS C:\Users\mwalters\development\email-service> node .\test.js                          

C:\Users\mwalters\development\email-service\node_modules\replify\replify.js:95          
      return logger.error('error making repl directory: ' + replDir, err)               
                                                            ^                           
ReferenceError: replDir is not defined                                                  
    at C:\Users\mwalters\development\email-service\node_modules\replify\replify.js:95:61
    at Object.oncomplete (fs.js:107:15)                                                 
```

changing to

```
return logger.error('error making repl directory: ' + options.path, err)
```

on line 95 should get rid of that, leaving just the following error:

```
PS C:\Users\mwalters\development\email-service> node .\test.js                                                                  
error making repl directory: /tmp/repl { [Error: ENOENT, mkdir 'C:\tmp\repl'] errno: 34, code: 'ENOENT', path: 'C:\\tmp\\repl' }
```

which is issue 1. 

Passing in an existing folder path results in the following error: 

```
PS C:\Users\mwalters\development\email-service> node .\test.js                                 
repl server error { [Error: listen EACCES] code: 'EACCES', errno: 'EACCES', syscall: 'listen' }
```

which should be covered by issue #9.

Thanks.

**Comment by togakangaroo** [comment]
Just ran into this as well trying to run jsbin on windows. Thanks.

**Comment by dshaw** [comment]
@togakangaroo Want to take a shot a at PR?
